var EmojiAnims = [
    [
        "(cool)",
        "cool.png",
        "Cool"
    ],
    [
        "(hearteyes)",
        "hearteyes.png",
        "Heart eyes"
    ],
    [
        "(stareyes)",
        "stareyes.png",
        "Star eyes"
    ],
    [
        "(like)",
        "like.png",
        "Like"
    ],
    [
        "(unamused)",
        "unamused.png",
        "Unamused"
    ],
    [
        "(cwl)",
        "cwl.png",
        "Crying with laughter"
    ],
    [
        "(xd)",
        "xd.png",
        "XD smiley"
    ],
    [
        ":)",
        "smile.png",
        "Smile"
    ],
    [
        ":(",
        "sad.png",
        "Sad"
    ],
    [
        ":D",
        "laugh.png",
        "Laugh"
    ],
    [
        ":O",
        "surprised.png",
        "Surprised"
    ],
    [
        ";)",
        "wink.png",
        "Wink"
    ],
    [
        ";(",
        "cry.png",
        "Crying"
    ],
    [
        "(shivering)",
        "shivering.png",
        "Cold shivering"
    ],
    [
        "(:|",
        "sweat.png",
        "Sweating"
    ],
    [
        ":|",
        "speechless.png",
        "Speechless"
    ],
    [
        ":P",
        "tongueout.png",
        "Cheeky"
    ],
    [
        ":$",
        "blush.png",
        "Blushing"
    ],
    [
        "(inlove)",
        "inlove.png",
        "In love"
    ],
    [
        "(kiss)",
        "kiss.png",
        "Kiss"
    ],
    [
        ":^)",
        "wonder.png",
        "Wondering"
    ],
    [
        "|-)",
        "sleepy.png",
        "Sleepy"
    ],
    [
        "|-(",
        "dull.png",
        "Dull"
    ],
    [
        "(yawn)",
        "yawn.png",
        "Yawn"
    ],
    [
        "(puke)",
        "puke.png",
        "Vomiting"
    ],
    [
        "(doh)",
        "doh.png",
        "Doh!"
    ],
    [
        "(angry)",
        "angry.png",
        "Angry"
    ],
    [
        "(wasntme)",
        "wasntme.png",
        "It wasn't me!"
    ],
    [
        "(worry)",
        "worry.png",
        "Worried"
    ],
    [
        "(mm)",
        "mmm.png",
        "Mmmmm…"
    ],
    [
        "(nerd)",
        "nerdy.png",
        "Nerdy"
    ],
    [
        "(rainbowsmile)",
        "rainbowsmile.png",
        "Rainbow smile"
    ],
    [
        ":x",
        "lipssealed.png",
        "My lips are sealed"
    ],
    [
        "(devil)",
        "devil.png",
        "Devil"
    ],
    [
        "(angel)",
        "angel.png",
        "Angel"
    ],
    [
        "(envy)",
        "envy.png",
        "Envy"
    ],
    [
        "(makeup)",
        "makeup.png",
        "Make-up"
    ],
    [
        "(think)",
        "think.png",
        "Thinking"
    ],
    [
        "(rofl)",
        "rofl.png",
        "Rolling on the floor laughing"
    ],
    [
        "(happy)",
        "happy.png",
        "Happy"
    ],
    [
        "(smirk)",
        "smirk.png",
        "Smirking"
    ],
    [
        "(nod)",
        "nod.png",
        "Nodding"
    ],
    [
        "(shake)",
        "shake.png",
        "Shake"
    ],
    [
        "(waiting)",
        "waiting.png",
        "Waiting"
    ],
    [
        "(emo)",
        "emo.png",
        "Emo"
    ],
    [
        "(donttalk)",
        "donttalktome.png",
        "Don't talk to me"
    ],
    [
        "(idea)",
        "idea.png",
        "Idea"
    ],
    [
        "(talk)",
        "talk.png",
        "Talking"
    ],
    [
        "(swear)",
        "swear.png",
        "Swearing"
    ],
    [
        "]:)",
        "evilgrin.png",
        "Evil grin"
    ],
    [
        "(headbang)",
        "headbang.png",
        "Banging head on wall"
    ],
    [
        "(learn)",
        "learn.png",
        "Global Learning"
    ],
    [
        "(headphones)",
        "headphones.png",
        "Listening to headphones"
    ],
    [
        "(morningafter)",
        "hungover.png",
        "Morning after party"
    ],
    [
        "(selfie)",
        "selfie.png",
        "Selfie"
    ],
    [
        "(shock)",
        "shock.png",
        "Spoiler alert"
    ],
    [
        "(llsshock)",
        "llsshock.png",
        "Spoiler alert"
    ],
    [
        "(ttm)",
        "ttm.png",
        "Talking too much"
    ],
    [
        "(dream)",
        "dream.png",
        "Dreaming"
    ],
    [
        "(ill)",
        "ill.png",
        "Ill"
    ],
    [
        "(tired)",
        "tired.png",
        "Tired"
    ],
    [
        "(party)",
        "party.png",
        "Party"
    ],
    [
        "(bandit)",
        "bandit.png",
        "Bandit"
    ],
    [
        "(tauri)",
        "tauri.png",
        "Bald man with glasses"
    ],
    [
        "(nazar)",
        "nazar.png",
        "Blessing"
    ],
    [
        "(movember)",
        "movember.png",
        "Movember"
    ],
    [
        "(mysteryskype)",
        "mysteryskype.png",
        "Mystery Skype"
    ],
    [
        "(dotdfemale)",
        "dotdfemale.png",
        "Day of the dead"
    ],
    [
        "(dotdmale)",
        "dotdmale.png",
        "Day of the dead"
    ],
    [
        "(selfiediwali)",
        "selfiediwali.png",
        "Selfie Diwali"
    ],
    [
        "(diwaliselfie)",
        "diwaliselfie.png",
        "Diwali selfie"
    ],
    [
        "(steveaoki)",
        "steveaoki.png",
        "Steve Aoki"
    ],
    [
        "(aokijump)",
        "aokijump.png",
        "Aoki jump"
    ],
    [
        "(cakethrow)",
        "cakethrow.png",
        "Cake throw"
    ],
    [
        "(kolony)",
        "kolony.png",
        "Kolony"
    ],
    [
        "(joy)",
        "joy.png",
        "Joy"
    ],
    [
        "(anger)",
        "anger.png",
        "Anger"
    ],
    [
        "(sadness)",
        "sadness.png",
        "Sadness"
    ],
    [
        "(disgust)",
        "disgust.png",
        "Disgust"
    ],
    [
        "(fear)",
        "fear.png",
        "Fear"
    ],
    [
        "(hestonfacepalm)",
        "hestonfacepalm.png",
        "Heston facepalm"
    ],
    [
        "(heston)",
        "heston.png",
        "Heston Blumenthal"
    ],
    [
        "(stormtrooper)",
        "stormtrooper.png",
        "Storm trooper"
    ],
    [
        "(kyloren)",
        "kyloren.png",
        "Kylo Ren"
    ],
    [
        "(captainphasma)",
        "captainphasma.png",
        "Captain Phasma"
    ],
    [
        "(malthe)",
        "malthe.png",
        "Smiling man with glasses"
    ],
    [
        "(ladyvamp)",
        "ladyvampire.png",
        "Lady vampire"
    ],
    [
        "(vampire)",
        "vampire.png",
        "Vampire"
    ],
    [
        "(ghost)",
        "ghost.png",
        "Ghost"
    ],
    [
        "(skull)",
        "skull.png",
        "Skull"
    ],
    [
        "(pumpkin)",
        "pumpkin.png",
        "Pumpkin"
    ],
    [
        "(santa)",
        "santa.png",
        "Santa"
    ],
    [
        "(xmascwl)",
        "xmascwl.png",
        "Xmas crying with laughter"
    ],
    [
        "(festiveparty)",
        "festiveparty.png",
        "Festive party"
    ],
    [
        "(holidayspirit)",
        "holidayspirit.png",
        "Holiday spirit"
    ],
    [
        "(rudolfsurprise)",
        "rudolfsurprise.png",
        "Surprised Rudolf"
    ],
    [
        "(rudolfidea)",
        "rudolfidea.png",
        "Rudolf idea"
    ],
    [
        "(wtf)",
        "wtf.png",
        "WTF…"
    ],
    [
        "(smoking)",
        "smoke.png",
        "Smoking"
    ],
    [
        "(drunk)",
        "drunk.png",
        "Drunk"
    ],
    [
        "(finger)",
        "finger.png",
        "Finger"
    ],
    [
        "(oliver)",
        "oliver.png",
        "Man saying come on"
    ],
    [
        "(xmassarcastic)",
        "xmassarcastic.png",
        "Xmas sarcastic"
    ],
    [
        "(xmascry)",
        "xmascry.png",
        "Xmas cry"
    ],
    [
        "(wave)",
        "hi.png",
        "Hi"
    ],
    [
        "(highfive)",
        "highfive.png",
        "High five"
    ],
    [
        "(clap)",
        "clap.png",
        "Clapping"
    ],
    [
        "(sarcastic)",
        "sarcastic.png",
        "Sarcastic"
    ],
    [
        "(chuckle)",
        "giggle.png",
        "Giggle"
    ],
    [
        "(facepalm)",
        "facepalm.png",
        "Facepalm"
    ],
    [
        "(rock)",
        "rock.png",
        "Rock"
    ],
    [
        "(yn)",
        "fingerscrossed.png",
        "Fingers crossed"
    ],
    [
        "(listening)",
        "listening.png",
        "Listening"
    ],
    [
        "(wait)",
        "wait.png",
        "Wait"
    ],
    [
        "(whew)",
        "whew.png",
        "Relieved"
    ],
    [
        "(tmi)",
        "tmi.png",
        "Too much information"
    ],
    [
        "(call)",
        "call.png",
        "Call"
    ],
    [
        "(punch)",
        "punch.png",
        "Punch"
    ],
    [
        "(talktothehand)",
        "talktothehand.png",
        "Talk to the hand"
    ],
    [
        "(whistle)",
        "whistle.png",
        "Whistle"
    ],
    [
        "(slap)",
        "slap.png",
        "Slap"
    ],
    [
        "(lalala)",
        "lalala.png",
        "Lalala"
    ],
    [
        "(y)",
        "yes.png",
        "Yes"
    ],
    [
        "(n)",
        "no.png",
        "No"
    ],
    [
        "(handshake)",
        "handshake.png",
        "Handshake"
    ],
    [
        "(fistbump)",
        "fistbump.png",
        "Fist bump"
    ],
    [
        "(poke)",
        "poke.png",
        "Poke"
    ],
    [
        "(celebrate)",
        "handsinair.png",
        "Hands celebrating"
    ],
    [
        "(hearthands)",
        "hearthands.png",
        "Heart hands"
    ],
    [
        "(victory)",
        "victory.png",
        "Victory sign"
    ],
    [
        "(noworries)",
        "noworries.png",
        "No worries"
    ],
    [
        "(ok)",
        "ok.png",
        "OK"
    ],
    [
        "(pray)",
        "praying.png",
        "Praying"
    ],
    [
        "(flex)",
        "muscle.png",
        "Muscle"
    ],
    [
        "(ek)",
        "naturescall.png",
        "Nature's call"
    ],
    [
        "(woty)",
        "woty.png",
        "Woman of the year"
    ],
    [
        "(glassceiling)",
        "glassceiling.png",
        "Glass ceiling"
    ],
    [
        "(deadyes)",
        "deadyes.png",
        "Dead yes"
    ],
    [
        "(xmasyes)",
        "xmasyes.png",
        "Xmas yes"
    ],
    [
        "(dropthemic)",
        "dropthemic.png",
        "Drop the mic"
    ]
];

export default EmojiAnims;